// apps/frontend/src/views/share.vue
<template>
    <Combo :notation="comboString" class="mb-10"/>

    <h2 class="text-lg mb-2">
        Share your combo
    </h2>

    <input
        type="text"
        placeholder="Enter Tekken Notation here"
        class="block input input-bordered w-full mb-4"
        :value="comboString"
        @input="handleComboInput"
    />

    <div class="alert">
        <div>
            <a
                :href="comboUrl"
                class="link link-accent px-2"
            >
                {{ comboUrl }}
            </a>
        </div>
        <div class="flex-none">
            <button
                class="btn btn-sm"
                @click="handleCopyClick"
            >
                Copy
            </button>
        </div>
    </div>
</template>

<script lang="ts" setup>
import { computed, onMounted, ref } from 'vue';
import { useRoute, useRouter } from 'vue-router';

import Combo from '@/components/combo.vue';

const router = useRouter();
const route = useRoute();

const comboString = ref<string>('');

onMounted(() => {
    comboString.value = route.query.combo as string || '';
});

const comboUrl = computed(() => {
    return `${window.location.origin}/#/share?combo=${encodeURIComponent(comboString.value)}`
});

function handleComboInput(event: any) {
    comboString.value = event.target.value;
    router.replace(`/share?combo=${comboString.value}`);
}

async function handleCopyClick() {
    try {
        await navigator.clipboard.writeText(comboUrl.value);
    } catch (error) {
        console.error('Failed to copy text.');
    }
}
</script>

// apps/frontend/app/share/page.tsx
'use client';

import { Form, Formik } from 'formik';
import { useRouter, useSearchParams } from 'next/navigation';

import ContainerLayout from '@/layouts/container-layout';
import TkNotationField from '@/ui/forms/notation-field';
import TsButton from '@/ui/buttons/button';

interface ShareComboValues {
    notation: string;
}

export default function Share() {
    const router = useRouter();
    const params = useSearchParams();

    const initialValues: ShareComboValues = {
        notation: decodeURIComponent((params?.get('notation') as string) || ''),
    };

    const handleInput = async (event: any) => {
        const encodedNotation = encodeURIComponent(event.target.value);

        await router.replace(`/share?notation=${encodedNotation}`);
    };

    const handleSubmit = async () => {
        try {
            await navigator.clipboard.writeText(window.location.href);
        } catch (error: any) {
            console.error(error);
        }
    };

    return (
        <ContainerLayout>
            <div className="prose prose-teal prose-invert mb-8">
                <h1>Share Combo</h1>
                <p>
                    Enter the notation for the combo you want to share and click
                    the &quot;Copy Share Link&quot; button. The link to your
                    combo will be copied to the clipboard.
                </p>
            </div>

            <Formik
                initialValues={initialValues}
                onSubmit={handleSubmit}
            >
                <Form>
                    <TkNotationField
                        name={'notation'}
                        placeholder={'Enter the combo notation, i.e.: d/f2,1+2'}
                        autoComplete={'off'}
                        autoCorrect={'off'}
                        onInput={handleInput}
                    />

                    <TsButton type={'submit'}>Copy Share Link</TsButton>
                </Form>
            </Formik>
        </ContainerLayout>
    );
}
