// __legacy/src/components/instruction.vue
<template>
    <div class="flex flex-col items-center gap-2">
        <img
            v-if="instruction.type !== 'special'"
            :src="iconUrl"
            class="w-12 h-12"
            :class="props.instruction.type"
            :alt="props.instruction.slug"
            :title="props.instruction.slug"
        />
        <div
            v-else
            class="flex items-center h-12"
        >
            <div :class="props.instruction.type">
                {{ props.instruction.slug }}
            </div>
        </div>

        <div class="h-5">
            {{ props.instruction.notation }}
        </div>
    </div>
</template>

<script lang="ts" setup>
import { defineProps, computed } from 'vue';
import { usePreferencesStore } from '@/store/preferences';

interface Props {
    instruction: any;
}

const props = defineProps<Props>();
const preferences = usePreferencesStore();

const iconUrl = computed(() => {
    const { slug } = props.instruction;

    switch (props.instruction.type) {
        case 'action':
            return `/icons/${preferences.layout}/${slug}.svg`;
        case 'movement':
            return `/icons/movement/${slug}.svg`;
        default:
            return `/icons/${slug}.svg`;
    }
});

console.log(props.instruction)
</script>

<style lang="scss">
.action {
    @apply mx-1;
}

.movement {

}

.special {
    @apply bg-black/50;
    @apply px-2 py-1 mx-2;
    @apply font-bold text-xs uppercase;
    @apply rounded-sm;
}
</style>

// apps/frontend/components/move-display/instruction.tsx
'use client';

import type { TekkenInstruction } from '@tekken-space/notation-parser';
import { TekkenInstructionType } from '@tekken-space/notation-parser';
import { useSelector } from 'react-redux';

import { selectUserPreferences } from '@/store/slices/users-slice';
import ActionControls from '@/components/controls/action-controls';
import MovementControls from '@/components/controls/movement-controls';

export enum ControllerLayout {
    UNKNOWN = 'UNKNOWN',
    GAMEPAD = 'GAMEPAD',
    XBOX = 'XBOX',
    PLAYSTATION = 'PLAYSTATION',
    ARCADE = 'ARCADE',
    HITBOX = 'HITBOX',
}

interface Props {
    instruction: TekkenInstruction;
}

export default function Instruction(props: Props) {
    const preferences = useSelector(selectUserPreferences);
    const scheme = preferences?.controllerLayout ?? ControllerLayout.GAMEPAD;

    const instructionText = props.instruction.notation.replace(/"/g, '');

    if (props.instruction.type === TekkenInstructionType.HIDDEN) {
        return null;
    }

    return (
        <div className={'flex flex-col items-center gap-2'}>
            {props.instruction.type === TekkenInstructionType.UNKNOWN && (
                <div className={'flex h-full items-center'}>
                    <div
                        className={
                            'mx-2 rounded-sm bg-black/50 px-2 py-1 text-xs font-bold uppercase'
                        }
                    >
                        {instructionText}
                    </div>
                </div>
            )}

            {props.instruction.type === TekkenInstructionType.CONTROL && (
                <div className={'flex h-full items-center'}>
                    <div
                        className={
                            'mx-2 mb-3 rounded-sm text-4xl font-bold uppercase leading-none'
                        }
                    >
                        {instructionText}
                    </div>
                </div>
            )}

            {props.instruction.type === TekkenInstructionType.ACTION && (
                <ActionControls
                    scheme={scheme}
                    inputs={props.instruction.inputs}
                />
            )}

            {props.instruction.type === TekkenInstructionType.MOVEMENT && (
                <MovementControls slug={props.instruction.slug} />
            )}
        </div>
    );
}
