// apps/frontend/components/move-display/move.tsx
import { FC } from 'react';
import { TekkenMove } from '@tekken-space/notation-parser';
import { TbChevronRight } from 'react-icons/tb';

import Instruction, {
    ControllerLayout,
} from '@/components/move-display/instruction';

interface Props {
    move: TekkenMove;
    layout?: ControllerLayout;
}

const Move: FC<Props> = (props) => {
    return (
        <div className="group mr-2 -ml-1 inline-flex gap-2">
            {props.move.instructions.map((instruction, index) => (
                <Instruction
                    key={index}
                    instruction={instruction}
                />
            ))}

            <div className="mr-2 flex items-center px-2 group-last:hidden">
                <TbChevronRight />
            </div>
        </div>
    );
};

export default Move;

// __legacy/src/components/move.vue
<template>
    <div class="inline-flex mr-2 -ml-1 group">
        <Instruction
            v-for="(instruction, index) in props.move.instructions"
            :key="index"
            :instruction="instruction"
        />

        <div class="pl-3 pr-2 group-last:hidden">
            <img
                src="/icons/follow.svg"
                class="h-10"
                alt="Next Move"
            />
        </div>
    </div>
</template>

<script lang="ts" setup>
import { defineProps } from 'vue';

import Instruction from '@/components/instruction.vue';

interface Props {
    move: any;
}

const props = defineProps<Props>();
</script>
